### ISSUE TITLE
How can I change colors of a theme?

### ISSUE THREAD

**Issue by xikeda** [jamesmfriedman/rmwc#212]
How can I change the theme or the primary/secondary/ etc colors of the RMWC? For instance my tool bar, buttons and button text is purple. How can I change that to blue?

**Comment by jamesmfriedman** [comment]
Please read the docs before filing an issue.

https://jamesmfriedman.github.io/rmwc/styling

**Comment by xikeda** [comment]
lol

**Comment by xikeda** [comment]
👎

**Comment by xikeda** [comment]
Read your docs. No help

**Comment by jamesmfriedman** [comment]
@xikeda, inspect the root element of html document.

Include this in your own CSS, a style tag, or however you get styles into your app.

```css
:root {
  --mdc-theme-primary: red;
  --mdc-theme-secondary: blue;
  // there are many more of these... refer to the mdc docs on the full list, or just look in your web inspector.
}
```

What would have helped that you didn't see in the docs about this?
