### ISSUE TITLE
RMWC classes not adding properly

### ISSUE THREAD

**Issue by progrmoiz** [jamesmfriedman/rmwc#253]
RMWC is adding classes before MDC classes
I wanted to change the height of `<TopAppBarRow>` by adding a class.
```jsx
<TopAppBarRow className="my-custom-header"></TopAppBarRow>
```
output
```html
<div class="my-custom-header mdc-top-app-bar__row"></div>
```
css
```css
.my-custom-header {
    height: 74px;
}
```
So, my styles cannot override mdc styles.
