### ISSUE TITLE
Customize drawer width in RMWC

### ISSUE THREAD

**Issue by marcel-k** [jamesmfriedman/rmwc#456]
Hi,

MDC release 0.40 added the feature of customising a drawers width. How would I do this in RMWC? 
I'm using a drawer and drawer-content, importing all the needed CSS in JS and am using styled-components to add or overwrite styles if need be.

Is it possible to set the width of a drawer in RMWC and how would I do this? Or do I need to work with the MDC SaSS variables? Would like to avoid adding SaSS to my project if that is possible.

This would be a feature request I think :)

Thx for the great work btw!

**Comment by jamesmfriedman** [comment]
you don't need the sass if you don't mind fixing it with a bit of CSS. The drawer itself is easy, but you might need to find the right selector combo if you want to adjust DrawerAppContent

```jsx
<Drawer style={{width: '500px'}}>
   ...
</Drawer>
```

If you are using DrawerAppContent, you'll want to do something like this. I just copy and pasted this out of my devtools
```css
.mdc-drawer.mdc-drawer--open:not(.mdc-drawer--closing) + .mdc-drawer-app-content {
  margin-left: 500px;
}
```
