### ISSUE TITLE
Can't configure RadioButton or Checkbox the use Primary theme and not secondary 

### ISSUE THREAD

**Issue by alexlipnik4** [jamesmfriedman/rmwc#474]
Is there a way to do it? right now i'm changing the secondary color in options passed to themeProvider that wrap the component but that's not a good practice. I feel like there is a way to just tell the component to use Primary color and not secondary, just couldn't find it on the documentation.  

 i also tried to wrap the Checkbox/RadioButton with Theme component, and tries to pass theme prop but it didn't work ass well. 

any help will be great!

**Comment by jamesmfriedman** [comment]
This is where we can have some fun with CSS Vars. For the scope of the checkbox (or whatever else you want). Just add some global CSS that resets the variable to a new value. In this case the new value is actually also a variable, our primary palette.

```css
.mdc-checkbox {
    --mdc-theme-secondary: var(--mdc-theme-primary, 'red' /** fallback color */);
}
```

You can apply the same behavior to anything in RMWC that responds to css variables.
