### ISSUE TITLE
SimpleListItem Icon wrong spacing

### ISSUE THREAD

**Issue by cmnstmntmn** [jamesmfriedman/rmwc#542]
**mdc-list**

I'm having the same issue with icon spacing inside a `<SimpleListItem />` like this one:
https://github.com/callstack/react-native-paper/issues/1003

this is the actual css style of the icon

```css
.mdc-list-item__graphic {
    margin-left: 0;
    margin-right: 32px; /* <---- this is causing the glitch */
    width: 24px;
    height: 24px;
    flex-shrink: 0;
    -webkit-box-align: center;
    align-items: center;
    -webkit-box-pack: center;
    justify-content: center;
    fill: currentColor;
}
```
