### ISSUE TITLE
Style overrides use CSS variables that might not be set

### ISSUE THREAD

**Issue by nicholaschiang** [jamesmfriedman/rmwc#659]
- What RMWC Version are you using [major.minor.patch]: 6.0.14

- Name your build system [Webpack, Rollup...]: Default that comes with Next.js (I think it's webpack).

- Describe the bug with as much detail as possible:

The styles included in `@rmwc/data-table/data-table.css` reference the global MDC theme variables that might not be set.

For example, I use Sass to set my theme like so:

```scss
@use '@material/theme' with (
  $primary: #0070f3,
  $secondary: #0070f3,
);
@use '@material/switch/mdc-switch';
```

That works fine for the actual `@material` styles (because they're also using Sass and reference the `@material/theme` mixins that are set when I import `@material/theme`). But RMWC references the global theme variables that aren't being set when I use this approach:

```css
/** Switch */
.rmwc-data-table__cell .mdc-switch {
  vertical-align: middle;
  margin-left: 0.5rem;
  --mdc-theme-secondary: var(--mdc-theme-primary, #6200ee);
}
```

You should, in the future, re-write your styling definitions to use Sass and reference the `@material/theme` mixins (like the official library does).

Or, just open issues in the official library so that you don't have to create these custom stylings at all.

- What happens and what is supposed to happen

Because those global variables haven't been set, the custom styles fallback to the default color theme instead of using the theme that I specify when importing `@material/theme`.
